apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: explorewithnk-com
  namespace: istio-system
spec:
  secretName: explorewithnk-com-tls # ğŸ” This must match Gateway's credentialName
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: explorewithnk.com
  dnsNames:
  - explorewithnk.com
  - "*.explorewithnk.com"
